# Generated by Django 4.0.2 on 2022-02-08 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_kategorie_kategorien_rename_produkt_produkte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategorien',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='produkte',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.kategorien'),
        ),
        migrations.AddField(
            model_name='produkte',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='produkte',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='produkte',
            name='prozent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='produkte',
            name='subcategorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.unterkategorien'),
        ),
        migrations.AddField(
            model_name='unterkategorien',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='unterkategorien',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='kategorien',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='unterkategorien',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.kategorien'),
        ),
    ]
