# Generated by Django 4.0.2 on 2022-02-10 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_kategorien_name_produkte_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkte',
            name='subcategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.unterkategorien'),
        ),
    ]
