# Generated by Django 4.0.2 on 2022-02-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_produkte_subcategorie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategorien',
            options={'verbose_name': 'Kategorie', 'verbose_name_plural': 'Kategorien'},
        ),
        migrations.AlterModelOptions(
            name='produkte',
            options={'verbose_name': 'Produkt', 'verbose_name_plural': 'Produkte'},
        ),
        migrations.AlterModelOptions(
            name='unterkategorien',
            options={'verbose_name': 'Unterkategorie', 'verbose_name_plural': 'Unterkategorien'},
        ),
    ]
