# Generated by Django 4.0.2 on 2022-02-10 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_kategorien_options_alter_produkte_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkte',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
