# Generated by Django 4.0.2 on 2022-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_produkte_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkte',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
