# Generated by Django 4.0.2 on 2022-02-26 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_produkte_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
