# Generated by Django 4.0.2 on 2022-02-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_cocktails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkte',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
