# Generated by Django 4.0.2 on 2022-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_cocktails_preis_produkte_preis1_produkte_preis2'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktails',
            name='_zutaten',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
