# Generated by Django 4.0.2 on 2022-02-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_cocktails__zutaten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktails',
            name='preis',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
